apps/base/urls.py
from django.urls import path

from apps.base import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('edit/<int:task_id>', views.edit_task, name='edit_task'),
    path('delete/<int:task_id>', views.delete_task, name='delete_task'),
]

testDjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.base.urls'))
]

apps/base/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Status(models.TextChoices):
        OPENED = "OP"
        IN_PROGRESS = "IP"
        PAUSED = "PA"
        COMPLETED = "CO"

    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.OPENED,
    )

apps/base/forms.py
from django.forms import ModelForm
from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'status')
        # labels= {'title': '',
        #          'description': '',
        #          'status': ''}

apps/base/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Task
from .forms import TaskForm


def index(request):
    paginator = Paginator(Task.objects.order_by("-date_added"), 6)
    page = request.GET.get('page')

    # tasks = Task.objects.order_by('-date_added')
    try:
        tasks = paginator.get_page(page)
    except EmptyPage:
        tasks = paginator.get_page(1)
    except PageNotAnInteger:
        tasks = paginator.get_page(1)
    except ValueError:
        tasks = paginator.get_page(1)

    context = {"title": "Home", "tasks": tasks, "page_obj": tasks}

    return render(request=request,
                  template_name="index.html",
                  context=context)


def new(request):
    if request.method != "POST":
        # No data was submitted - create an empty form
        form = TaskForm()
    else:
        # Got data from POST-request; Process data
        form = TaskForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("base:index")

    context = {"title": "New", "form": form}
    return render(request=request,
                  template_name="new.html",
                  context=context)


def edit_task(request, task_id):
    if request.method == "POST":
        form = TaskForm(request.POST, instance=Task.objects.get(id=task_id))
        if form.is_valid():
            form.save()
            return redirect('base:index')
    else:
        form = TaskForm(instance=Task.objects.get(id=task_id))
        return render(request=request,
                      template_name='edit_task.html',
                      context={"title": "Edit", "form": form, "task_id": task_id})


def delete_task(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method == "POST":
        task.delete()
        return redirect("base:index")
    else:
        return render(request=request,
                      template_name='delete_task.html',
                      context={"title": "Delete", "task": task}
                      )

apps/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block Head %}{% endblock %}
    <title>SiteName{% if title %} | {{ title }}{% endif %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">

</head>
<body>
<header>
    <h1 style="text-align: center">Our Site</h1>
    <div style="text-align: center">
        <a href="{% url 'base:index' %}">Home</a> |
        <a href="{% url 'base:new' %}"> New Task</a>
    </div>
    <hr>
</header>
{% block Body %}{% endblock %}
</body>
</html>

apps/templates/delete_task.html
{% extends "base.html" %}

{% block Body %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title text-danger">Confirm delete</h2>
                        <p class="card-text">Are you sure you want delete "{{ task.title }}"?</p>
                        <div class="d-flex justify-content-around mt-4">
                            <form method="post" action="{% url 'base:delete_task' task.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Confirm</button>
                            </form>
                            <a href="{% url 'base:index' %}" class="btn btn-light border">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/edit_task.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block Body %}
    <h1 style="text-align: center">Edit task</h1>
    <form style="width: 40em; margin: auto" method="post" action="{% url 'base:edit_task' task_id %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
{% endblock %}

apps/templates/index.html
{% extends "base.html" %}

{% block Body %}
    <h1 class="text-center">Tasks page</h1>
    <div class="container">
        <div class="row">
            {% for task in tasks %}
                <div class="col-md-4 mb-4">
                    <div class="card text-center">
                        <div class="card-body">
                            {% if task.status == "OP" %}
                                <h2 class="card-title" style="color: #29c8e1">Opened</h2>
                            {% elif task.status == "IP" %}
                                <h2 class="card-title" style="color: #fca400">In Progress</h2>
                            {% elif task.status == "PA" %}
                                <h2 class="card-title" style="color: #f42c17">Paused</h2>
                            {% elif task.status == "CO" %}
                                <h2 class="card-title" style="color: #00fc2a">Completed</h2>
                            {% endif %}
                            <h3>{{ task.title }}</h3>
                            <h5>{{ task.date_added|date:"H:i  M d, Y" }}</h5>
                            <p class="card-text">{{ task.description }}</p>
                            <a class="btn btn-primary" href="{% url 'base:edit_task' task.id %}">Edit</a>
                            <a class="btn btn-danger" href="{% url 'base:delete_task' task.id %}">Delete</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="d-flex justify-content-center mt-4">
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1"> << </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"> < </a>
                    </li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"> > </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> >> </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

apps/templates/new.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block Body %}
    <h1 style="text-align: center">Add a new task:</h1>
    <form style="margin: auto; width: 40em" action="{% url 'base:new' %}" method="post">
        {% csrf_token %} {{ form|crispy }}
        <button class="btn btn-primary" name="submit">New task</button>
    </form>
{% endblock Body %}